export const supabaseUrl = 'https://lbkluahlpbeajlpwkgsm.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxia2x1YWhscGJlYWpscHdrZ3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTI2OTYsImV4cCI6MjA1ODQyODY5Nn0.gBPwgEO4KLOUzLLBCSKie7Bu0Gt4IRBjkOM0bTTUrXg';
